import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useForm } from "react-hook-form";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm();
  const onSubmit = (data) => {
    axios
      .post("http://localhost:8000/user/add", data)
      .then((response) => console.log(response.data))
      .catch((error) => console.error(error));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="w-full max-w-md mx-auto"
          >
            <div className="grid grid-cols-2 gap-4">
              <label
                htmlFor="firstName"
                className="block font-medium text-gray-700"
              >
                Firstname:
              </label>
              <input
                type="text"
                {...register("firstName", { required: true })}
                className="form-input mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
              />
              {errors.firstName && <p>This field is required</p>}
              <br />
              <label htmlFor="lastName">Lastname:</label>
              <input
                type="text"
                {...register("lastName", { required: true })}
              />
              {errors.lastName && <p>This field is required</p>}
              <br />
              <label htmlFor="email">Email:</label>
              <input
                type="email"
                id="email"
                {...register("email", {
                  required: true,
                  pattern: /^\S+@\S+$/i
                })}
              />
              {errors.email && (
                <p>Please enter a valid email address and can not be empty</p>
              )}
              <br />
              <label htmlFor="phoneNum">Phone Number:</label>
              <input
                {...register("phoneNum", {
                  pattern: {
                    value: /^[0-9]{10}$/i,
                    message: "Invalid phone number"
                  }
                })}
              />
              {errors.phoneNum && <p>Invalid phone number</p>}
              <br />
              <br />
              <input type="submit" />{" "}
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
